name: Run Jupyter Notebook
on: [push]

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install numpy pandas scikit-learn jupyter opencv-python wandb

      - name: Convert and run Jupyter Notebook
        run: |
          jupyter nbconvert --to script distance_classification.ipynb
          python distance_classification.py
